export const categorias = [
  { id: "panaderia", nombre: "Panadería" },
  { id: "granos", nombre: "Arroz y granos" },
  { id: "verduras", nombre: "Verduras" },
  { id: "frutas", nombre: "Frutas" },
  { id: "bebidas", nombre: "Bebidas" },
  { id: "despensa", nombre: "Despensa" },
];

export const productos = [
  {
    id: "pan-tajado",
    nombre: "Pan tajado 600 g",
    precio: 8900,
    unidad: "paquete",
    categoria: "panaderia",
    stock: 18,
    imagen: "/productos/pan-tajado.jpg",
  },
  {
    id: "pan-queso",
    nombre: "Pan de queso x 6",
    precio: 7200,
    unidad: "bolsa",
    categoria: "panaderia",
    stock: 4,
    imagen: "/productos/pan-queso.jpg",
  },
  {
    id: "arepa-mote",
    nombre: "Arepa de mote x 5",
    precio: 4500,
    unidad: "paquete",
    categoria: "panaderia",
    stock: 0,
    imagen: "/productos/arepa-mote.jpg",
  },
  {
    id: "arroz-blanco",
    nombre: "Arroz blanco 500 g",
    precio: 2800,
    unidad: "bolsa",
    categoria: "granos",
    stock: 25,
    imagen: "/productos/arroz-blanco.jpg",
  },
  {
    id: "arroz-integral",
    nombre: "Arroz integral 1 kg",
    precio: 6200,
    unidad: "bolsa",
    categoria: "granos",
    stock: 0,
    imagen: "/productos/arroz-integral.jpg",
  },
  {
    id: "frijol",
    nombre: "Fríjol cargamanto 500 g",
    precio: 7000,
    unidad: "bolsa",
    categoria: "granos",
    stock: 12,
    imagen: "/productos/frijol.jpg",
  },
  {
    id: "tomate",
    nombre: "Tomate chonto 1 lb",
    precio: 3500,
    unidad: "lb",
    categoria: "verduras",
    stock: 8,
    imagen: "/productos/tomate.jpg",
  },
  {
    id: "cilantro",
    nombre: "Cilantro fresco",
    precio: 1500,
    unidad: "manojo",
    categoria: "verduras",
    stock: 3,
    imagen: "/productos/cilantro.jpg",
  },
  {
    id: "papa-criolla",
    nombre: "Papa criolla 1 lb",
    precio: 6500,
    unidad: "lb",
    categoria: "verduras",
    stock: 0,
    imagen: "/productos/papa-criolla.jpg",
  },
  {
    id: "platano",
    nombre: "Plátano hartón",
    precio: 2800,
    unidad: "unidad",
    categoria: "verduras",
    stock: 15,
    imagen: "/productos/platano.jpg",
  },
  {
    id: "lechuga",
    nombre: "Lechuga crespa",
    precio: 3200,
    unidad: "unidad",
    categoria: "verduras",
    stock: 0,
    imagen: "/productos/lechuga.jpg",
  },
  {
    id: "banano",
    nombre: "Banano urabá x 6",
    precio: 4500,
    unidad: "manojo",
    categoria: "frutas",
    stock: 6,
    imagen: "/productos/banano.jpg",
  },
  {
    id: "aguacate",
    nombre: "Aguacate papero",
    precio: 4500,
    unidad: "unidad",
    categoria: "frutas",
    stock: 5,
    imagen: "/productos/aguacate.jpg",
  },
  {
    id: "agua",
    nombre: "Agua 600 ml",
    precio: 1800,
    unidad: "botella",
    categoria: "bebidas",
    stock: 30,
    imagen: "/productos/agua.jpg",
  },
  {
    id: "gaseosa",
    nombre: "Gaseosa 1.5 L",
    precio: 6900,
    unidad: "botella",
    categoria: "bebidas",
    stock: 9,
    imagen: "/productos/gaseosa.jpg",
  },
  {
    id: "jugo",
    nombre: "Jugo de mora 1 L",
    precio: 4200,
    unidad: "caja",
    categoria: "bebidas",
    stock: 0,
    imagen: "/productos/jugo.jpg",
  },
  {
    id: "cafe",
    nombre: "Café molido 250 g",
    precio: 12900,
    unidad: "bolsa",
    categoria: "bebidas",
    stock: 7,
    imagen: "/productos/cafe.jpg",
  },
  {
    id: "leche",
    nombre: "Leche entera 1 L",
    precio: 4800,
    unidad: "bolsa",
    categoria: "despensa",
    stock: 4,
    imagen: "/productos/leche.jpg",
  },
  {
    id: "huevos",
    nombre: "Huevos criollos x 12",
    precio: 9600,
    unidad: "cubeta",
    categoria: "despensa",
    stock: 11,
    imagen: "/productos/huevos.jpg",
  },
  {
    id: "aceite",
    nombre: "Aceite vegetal 1 L",
    precio: 14900,
    unidad: "botella",
    categoria: "despensa",
    stock: 0,
    imagen: "/productos/aceite.jpg",
  },
];
